### ISSUE TITLE
Missing file?

### ISSUE THREAD

**Issue by houshuang** [lachand/ABCDE.angular#1]
Trying to get this to run locally. Don't have much experience with Angular or TS - I might be doing something wrong.

```js
~/s/Toccata (master) $ npm install
[fsevents] Success: "/Users/stian/src/Toccata/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
[sqlite3] Success: "/Users/stian/src/Toccata/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node" is installed via remote
prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/leveldown-v2.1.1-node-v57-darwin-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/stian/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v2.1.1-leveldown-v2.1.1-node-v57-darwin-x64.tar.gz
prebuild-install http request GET https://github.com/level/leveldown/releases/download/v2.1.1/leveldown-v2.1.1-node-v57-darwin-x64.tar.gz
prebuild-install http 200 https://github.com/level/leveldown/releases/download/v2.1.1/leveldown-v2.1.1-node-v57-darwin-x64.tar.gz
prebuild-install info downloading to @ /Users/stian/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v2.1.1-leveldown-v2.1.1-node-v57-darwin-x64.tar.gz.11502-eafaddc0f92d7.tmp
prebuild-install info renaming to @ /Users/stian/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v2.1.1-leveldown-v2.1.1-node-v57-darwin-x64.tar.gz
prebuild-install info unpacking @ /Users/stian/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v2.1.1-leveldown-v2.1.1-node-v57-darwin-x64.tar.gz
prebuild-install info unpack resolved to /Users/stian/src/Toccata/node_modules/leveldown/build/Release/leveldown.node
prebuild-install info unpack required /Users/stian/src/Toccata/node_modules/leveldown/build/Release/leveldown.node successfully
prebuild-install info install Successfully installed prebuilt binary!
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/darwin-x64-57_binding.node
Download complete
Binary saved to /Users/stian/src/Toccata/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Caching binary to /Users/stian/.npm/node-sass/4.7.2/darwin-x64-57_binding.node
(node:11413) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
Binary found at /Users/stian/src/Toccata/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Testing binary
Binary is fine
Date: 2018-03-21T06:24:08.587Z
Hash: 69ab3b0ee46fa16429d5
Time: 157267ms
chunk {0} main.9e3a37a4151af9204cd6.bundle.js (main) 2.08 MB [initial] [rendered]
chunk {1} polyfills.6fb40b5fe9a282093cfa.bundle.js (polyfills) 84.4 kB [initial] [rendered]
chunk {2} styles.60fe9dcc651f666eb1a5.bundle.css (styles) 47 kB [initial] [rendered]
chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]
added 2455 packages in 255.952s
```

```js
~/s/Toccata (master) $ node_modules/.bin/ng serve
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 27% building modules 148/175 modules 27 active .../pouchdb-find/lib/index-browser.es.jswebpack: wait until bundle finished: /
Date: 2018-03-21T06:25:20.259Z
Hash: b74fc3afe65c9637c521
Time: 31476ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 932 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 797 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 294 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 21.2 MB [initial] [rendered]

ERROR in ./node_modules/jqwidgets-scripts/jqwidgets-ts/angular_jqxkanban.ts
Module build failed: Error: /Users/stian/src/Toccata/node_modules/jqwidgets-scripts/jqwidgets-ts/angular_jqxkanban.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/stian/src/Toccata/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/Users/stian/src/Toccata/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/jqwidgets-scripts/jqwidgets-ts/angular_jqxsplitter.ts
Module build failed: Error: /Users/stian/src/Toccata/node_modules/jqwidgets-scripts/jqwidgets-ts/angular_jqxsplitter.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/stian/src/Toccata/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/Users/stian/src/Toccata/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

webpack: Failed to compile.
```

**Comment by lachand** [comment]
Hi,
Thanks for your feedback. I am going to look at this error today and create a real and simplified installation procedure this week.

**Comment by lachand** [comment]
I have modified the installation process and updated instructions for installation. It should work now.
